### PR TITLE
Fixed an issue with Rails 5.0.0 with missing content type which was causing NoMethodError: undefined method `symbol' for nil:NilClass  in ActionDispatch::Request 

### PR DESCRIPTION
**Pull request by bogdanRada**
The full backtrace of the error can be found here: https://gist.github.com/bogdanRada/426a8cd4f7d796d8498de3bf3501074a

i updated also Rakefile to be able to run appraisal tests directly and added Rails 5.0.0 for travis builds also.

Let me know what you think. Thank you very much.

### CODE REVIEW

**Comment by bogdanRada** [comment]
Sorry about so many commits, i forgot to push travis configuration for rails 5.0.0

**Comment by inossidabile** [comment]
No need to test against beta anymore. Please drop it.

**Comment by bogdanRada** [comment]
I updated travis and removed the beta version also have disabled the build for Jruby for Rails 5.0.0 since is not compatible and the build for Ruby 1.9.3 and Rails 4.0.0 since json gem doesn't seem to install. 
We should probably drop also ruby 1.9.3 since is not maintained anymore.

**Comment by bogdanRada** [comment]
thank you very much :)

**Pull request merged**
