### PR TITLE
Handle values of type 'int' the same as 'integer's.

### LINKED ISSUE #198: int/integer discrepancy
When generating the WSDL, all fields of type `integer` are expressed as `int`.
However, when parsing requests, wash_out requires the field to be of type `integer` (see https://github.com/inossidabile/wash_out/blob/master/lib/wash_out/param.rb#L66)

### PR DESCRIPTION
**Pull request by mhutter**
Fixes #198.

### CODE REVIEW

**Comment by inossidabile** [comment]
I don't think I understand. How's the visual DSL related to WSDL? Why introduce two possible notations for integer?

**Comment by mhutter** [comment]
I might have tracked the problem to the wrong location, but if you do something like this:

```ruby
  soap_action :do_something_else,
    args: { a: :int, b: :int },
    return: { result: :integer }
```
then `wash_out` will shit itself when parsing incoming requests:

    RuntimeError (Invalid WashOut simple type: int):

**Comment by inossidabile** [comment]
What makes you think you can use _int_ wording at all? If you put :green_dragon in it will shit itself as well. Bad gem! :)

**Comment by inossidabile** [comment]
Ok, I can see _int_ being used in Readme once indeed. We have to fix that instead I believe. I wouldn't like to introduce aliases fort simple types.

**Comment by mhutter** [comment]
Aaaah, I see! Yes, that's also a possibility. I assumed the types I can use in `soap_action` correspond with XML types (which indeed aliases `int` and `integer`)

**Pull request closed without merging**
