### PR TITLE
Option to change the service name

### PR DESCRIPTION
**Pull request by jesusabarca**
This PR resolves https://github.com/inossidabile/wash_out/issues/242 by adding a `service_name` configuration option, which allows to define a custom SOAP service name.

### CODE REVIEW

**Comment by ramanbuttar** [comment]
@inossidabile can this be merged in?

**Comment by jesusabarca** [comment]
It's been a year since I created this PR 😱

**Comment by dub357** [comment]
when is this gonna make it into the newest release?

**Comment by jesusabarca** [comment]
@dub357 seems like this project is pretty much abandoned. You can specify a `branch` option in your `Gemfile` pointing to master tho

**Comment by jesusabarca** [comment]
@inossidabile I can help with some maintenance with this project.

**Comment by inossidabile** [comment]
@jesusabarca can you fork it to your space and prepare README update with a forward?

**Pull request merged**
