### PR TITLE
Adds SOAP header parsing and rendering

### PR DESCRIPTION
**Pull request by yjukaku**
- Adds `:header_args` and `:header_return` options to `soap_action` to specify accepted header arguments and header rendering format
- Adds header tag to responses if `:header_return` option is specified
- Makes header tag data accessible from `params[:header]` in SOAP controller actions.

Addresses #157 

Please review!

### CODE REVIEW

**Comment by inossidabile** [comment]
Why do you want to make ppl specify headers manually if they are not involved into strict part of WSDL-building?

**Comment by yjukaku** [comment]
Sorry, I don't understand your question. Do you mind rewording it?

**Comment by inossidabile** [comment]
Why do you want a user to specify headers in the method specification?

**Comment by yjukaku** [comment]
Sometimes SOAP API's require responses in the SOAP Header (`<env:Header>` tags) as below:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="false" xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
  <env:Header>
    <value>12345</value>
  </env:Header>
  <env:Body>
    <tns:answer>
      <value>42</value>
     </tns:answer>
  </env:Body>
</env:Envelope>
```

They also may have incoming data in the SOAP Header as well, which is why I added `header_args` as well.

**Comment by inossidabile** [comment]
Yes. But as far as I remember it's not specified in WSDL. Why do you want user to specify something that's not even used? Why not just take everything from `<Header>` and put it to `params` or whatever? Let's not evolve useless SOAP complexity even further :).

**Comment by yjukaku** [comment]
Ah... I see! Hmm... good point.

After reading your comment and thinking about it, I wondered if WSDL's do have a way to specify headers. According to http://www.ibm.com/developerworks/library/ws-tip-headers/ there is a way, although I'm not sure it's even worth the complexity.

Would you be fine with just throwing the parsed XML into a hash and putting it in `params[:header]`?

**Comment by inossidabile** [comment]
It's not worth at all. Headers are flexible and let them be so.

So yes, having a helper to access them is a good idea, I don't mind that. I don't really see them in `params` though because it doesn't feel like a Rails-way. Can we mix them it into `request.soap_headers`? Or maybe a separate `soap_request`. I want it to mimic Rails as strong as possible. Hope it makes sense. Worst-case scenario that I'm ok to accept is a separate `soap_headers` method.

**Comment by yjukaku** [comment]
How about adding a `soap_request` helper method with `soap_request.headers` and `soap_request.body`, that returns `Hash`ed data?

**Comment by inossidabile** [comment]
Yes, works for me.

**Comment by inossidabile** [comment]
Any news?

**Comment by agnessa** [comment]
Thanks @yjukaku that comes just in time for me! Just a note, I disagree with @inossidabile that is is not worth it to represent headers in the WSDL; I'm with the author of the linked article on that: "Generally, however, it is considered a bad style to add parts to a SOAP message that are not contained in its WSDL definition". From a practical perspective, if I set up a service that expects to receive required headers, it is not enough for me to publish the WSDL for clients to know the required structure of messages, I also need to write an epic for them on the use of the headers.

**Comment by inossidabile** [comment]
@agnessa don't take this as offence but if you are to think about theoretical correctness of SOAP that's being used in Rails in 2017 - you are doing something terribly wrong with your time. I didn't read your article but it's clear from definition that if taken purely SOAP needs to be as strict as possible. And yes, this involves specification of headers and hopefully even the name of the dog of the user who's gonna call it.

That's exactly what makes **SOAP such a crap**. It had its time. But now, especially with Rails - using SOAP is an occasional practice that has to be forced on you by obstacles. Otherwise - **RUN AWAY FROM SOAP**.

In this regards WashOut is the last shelter only. It keeps SOAP implementation on a low profile just to be compatible. And not a single step further ever. I hope by this time I already made clear why.

For those of you who need very special WSDL - you can just take what's generated by WashOut, change it and use. You don't need zillions of meta instruments in WashOut. You need your text editor and a bit of creativeness only. Thankfully WashOut is very flexible in real-time parsing so it's most likely it will accept any request from any WSDL you formulate.

And thanks to @yjukaku you can even parse whatever headers you got with a handy helpers! Yay!

**Comment by agnessa** [comment]
No offence taken, I do agree with you in principle about technological choices, but there are times where the client has their own preferences. You'd be amazed how many organisations are out there who remain completely unimpressed by the calendar and SOAP is the only way to do integrations with their systems. Possibly the best course of action would have been to stick to java tooling for the job, but we decided to prototype with wash_out to get it off the ground faster. Inevitably, I learnt a thing or two about when not to use it.

**Comment by inossidabile** [comment]
Or like I said, just use your text editor. It's prototype, right? :)

**Pull request merged**
